### ISSUE TITLE
何らかの音声ファイルからWisper APIで文字起こしができる

### ISSUE THREAD

**Issue by ryo-1129** [itsp-pbl-2023/kagayaki#14]
## 取り組むこと
- 指定した音声ファイルを文字起こししてテキストを返すようなAPIを`/app/api/wisper/route.ts`に実装する
- 作成したAPIが実際に動作することをテストディレクトリで検証する

**Comment by aya-se** [comment]
ゴール：音声ファイルを入力として、文字起こしテキストをレスポンスとして返すようなAPIを作成する。
